name: Restrict Merge to Main

on:
  pull_request:
    branches:
      - main

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    name: Backend Build and Test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.101' # Specify the required .NET version

      - name: Restore Backend Dependencies
        working-directory: ./Roomiebill.Server # Adjust this path to your server directory
        run: dotnet restore

      - name: Build Backend
        working-directory: ./Roomiebill.Server
        run: dotnet build --no-restore --configuration Release

      - name: Test Backend
        working-directory: ./ServerTests # Adjust this path to your test project directory
        run: dotnet test ./ServerTests.csproj --verbosity normal

  frontend-build-and-test:
    runs-on: windows-latest # MAUI builds require Windows for full support
    name: Frontend (MAUI) Build and Test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.101' # Specify the required .NET version

      - name: Restore MAUI Dependencies
        working-directory: ./FrontendApplication # Adjust this path to your MAUI frontend directory
        run: dotnet restore

      - name: Build MAUI Frontend
        working-directory: ./FrontendApplication
        run: dotnet build --no-restore --configuration Release      

      - name: Test MAUI Frontend (Optional)
        working-directory: ./FrontendApplication
        run: |
          echo "Skipping tests for MAUI frontend (if no tests exist)"
          # Add tests if your MAUI frontend includes unit tests
        continue-on-error: true # Optional: If tests are unavailable

  final-checks:
    needs:
      - backend-build-and-test
      - frontend-build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Ensure All Checks Passed
        run: echo "All builds and tests passed successfully."
